apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-1
  namespace: argocd1
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-guestbook-1'
      namespace: argocd1
    spec:
      project: default
      source:
        repoURL: https://github.com/AayushiAsati/argo-cd-practice.git
        targetRevision: master
        path: argo-cd-practice
      destination:
        server: '{{server}}'
        namespace: guestbook-1
      syncPolicy:
         syncOptions:
          - CreateNamespace=true
